version: '3'
services:
  bounce:
    build:
      context: .
      dockerfile: bounce/Dockerfile
    environment:
     - "TIMESCALE_HOST=timescale"
    container_name: bounce-service
    entrypoint: /go/bin/bounce
    depends_on:
      - timescale
    links:
      - timescale
    ports:
      - "50000:8080"
  web:
    build:
      context: .
      dockerfile: web/Dockerfile
    environment:
     - "SRV_BOUNCE_ADDR=bounce:8080"
    image: pltvs/todo-web
    container_name: bounce-web
    depends_on:
      - bounce
    links:
      - bounce
    ports:
      - "3030:8080"
  timescale:
    image: timescale/timescaledb
    environment:
      POSTGRES_DB: dev
      POSTGRES_USER: test
      POSTGRES_PASSWORD: password
      TIMESCALEDB_TELEMETRY: 'off'
