// Code generated by protoc-gen-go. DO NOT EDIT.
// source: proto/bounce/service.proto

package bounce

import (
	context "context"
	fmt "fmt"
	proto "github.com/golang/protobuf/proto"
	grpc "google.golang.org/grpc"
	math "math"
)

// Reference imports to suppress errors if they are not otherwise used.
var _ = proto.Marshal
var _ = fmt.Errorf
var _ = math.Inf

// This is a compile-time assertion to ensure that this generated file
// is compatible with the proto package it is being compiled against.
// A compilation error at this line likely means your copy of the
// proto package needs to be updated.
const _ = proto.ProtoPackageIsVersion3 // please upgrade the proto package

type BounceGetData struct {
	AccountId            int32    `protobuf:"varint,1,opt,name=account_id,json=accountId,proto3" json:"account_id,omitempty"`
	XXX_NoUnkeyedLiteral struct{} `json:"-"`
	XXX_unrecognized     []byte   `json:"-"`
	XXX_sizecache        int32    `json:"-"`
}

func (m *BounceGetData) Reset()         { *m = BounceGetData{} }
func (m *BounceGetData) String() string { return proto.CompactTextString(m) }
func (*BounceGetData) ProtoMessage()    {}
func (*BounceGetData) Descriptor() ([]byte, []int) {
	return fileDescriptor_c01c9c31388ac37d, []int{0}
}

func (m *BounceGetData) XXX_Unmarshal(b []byte) error {
	return xxx_messageInfo_BounceGetData.Unmarshal(m, b)
}
func (m *BounceGetData) XXX_Marshal(b []byte, deterministic bool) ([]byte, error) {
	return xxx_messageInfo_BounceGetData.Marshal(b, m, deterministic)
}
func (m *BounceGetData) XXX_Merge(src proto.Message) {
	xxx_messageInfo_BounceGetData.Merge(m, src)
}
func (m *BounceGetData) XXX_Size() int {
	return xxx_messageInfo_BounceGetData.Size(m)
}
func (m *BounceGetData) XXX_DiscardUnknown() {
	xxx_messageInfo_BounceGetData.DiscardUnknown(m)
}

var xxx_messageInfo_BounceGetData proto.InternalMessageInfo

func (m *BounceGetData) GetAccountId() int32 {
	if m != nil {
		return m.AccountId
	}
	return 0
}

type BounceGetDataResponse struct {
	Reason                 string   `protobuf:"bytes,1,opt,name=reason,proto3" json:"reason,omitempty"`
	BounceClassName        string   `protobuf:"bytes,2,opt,name=bounce_class_name,json=bounceClassName,proto3" json:"bounce_class_name,omitempty"`
	BounceClassDescription string   `protobuf:"bytes,3,opt,name=bounce_class_description,json=bounceClassDescription,proto3" json:"bounce_class_description,omitempty"`
	OunceCategoryId        int32    `protobuf:"varint,4,opt,name=ounce_category_id,json=ounceCategoryId,proto3" json:"ounce_category_id,omitempty"`
	BounceCategoryName     string   `protobuf:"bytes,5,opt,name=bounce_category_name,json=bounceCategoryName,proto3" json:"bounce_category_name,omitempty"`
	ClassificationId       int32    `protobuf:"varint,6,opt,name=classification_id,json=classificationId,proto3" json:"classification_id,omitempty"`
	CountInbandBounce      int32    `protobuf:"varint,7,opt,name=count_inband_bounce,json=countInbandBounce,proto3" json:"count_inband_bounce,omitempty"`
	CountOutofbandBounce   int32    `protobuf:"varint,8,opt,name=count_outofband_bounce,json=countOutofbandBounce,proto3" json:"count_outofband_bounce,omitempty"`
	CountBounce            int32    `protobuf:"varint,9,opt,name=count_bounce,json=countBounce,proto3" json:"count_bounce,omitempty"`
	XXX_NoUnkeyedLiteral   struct{} `json:"-"`
	XXX_unrecognized       []byte   `json:"-"`
	XXX_sizecache          int32    `json:"-"`
}

func (m *BounceGetDataResponse) Reset()         { *m = BounceGetDataResponse{} }
func (m *BounceGetDataResponse) String() string { return proto.CompactTextString(m) }
func (*BounceGetDataResponse) ProtoMessage()    {}
func (*BounceGetDataResponse) Descriptor() ([]byte, []int) {
	return fileDescriptor_c01c9c31388ac37d, []int{1}
}

func (m *BounceGetDataResponse) XXX_Unmarshal(b []byte) error {
	return xxx_messageInfo_BounceGetDataResponse.Unmarshal(m, b)
}
func (m *BounceGetDataResponse) XXX_Marshal(b []byte, deterministic bool) ([]byte, error) {
	return xxx_messageInfo_BounceGetDataResponse.Marshal(b, m, deterministic)
}
func (m *BounceGetDataResponse) XXX_Merge(src proto.Message) {
	xxx_messageInfo_BounceGetDataResponse.Merge(m, src)
}
func (m *BounceGetDataResponse) XXX_Size() int {
	return xxx_messageInfo_BounceGetDataResponse.Size(m)
}
func (m *BounceGetDataResponse) XXX_DiscardUnknown() {
	xxx_messageInfo_BounceGetDataResponse.DiscardUnknown(m)
}

var xxx_messageInfo_BounceGetDataResponse proto.InternalMessageInfo

func (m *BounceGetDataResponse) GetReason() string {
	if m != nil {
		return m.Reason
	}
	return ""
}

func (m *BounceGetDataResponse) GetBounceClassName() string {
	if m != nil {
		return m.BounceClassName
	}
	return ""
}

func (m *BounceGetDataResponse) GetBounceClassDescription() string {
	if m != nil {
		return m.BounceClassDescription
	}
	return ""
}

func (m *BounceGetDataResponse) GetOunceCategoryId() int32 {
	if m != nil {
		return m.OunceCategoryId
	}
	return 0
}

func (m *BounceGetDataResponse) GetBounceCategoryName() string {
	if m != nil {
		return m.BounceCategoryName
	}
	return ""
}

func (m *BounceGetDataResponse) GetClassificationId() int32 {
	if m != nil {
		return m.ClassificationId
	}
	return 0
}

func (m *BounceGetDataResponse) GetCountInbandBounce() int32 {
	if m != nil {
		return m.CountInbandBounce
	}
	return 0
}

func (m *BounceGetDataResponse) GetCountOutofbandBounce() int32 {
	if m != nil {
		return m.CountOutofbandBounce
	}
	return 0
}

func (m *BounceGetDataResponse) GetCountBounce() int32 {
	if m != nil {
		return m.CountBounce
	}
	return 0
}

func init() {
	proto.RegisterType((*BounceGetData)(nil), "bounce.BounceGetData")
	proto.RegisterType((*BounceGetDataResponse)(nil), "bounce.BounceGetDataResponse")
}

func init() { proto.RegisterFile("proto/bounce/service.proto", fileDescriptor_c01c9c31388ac37d) }

var fileDescriptor_c01c9c31388ac37d = []byte{
	// 324 bytes of a gzipped FileDescriptorProto
	0x1f, 0x8b, 0x08, 0x00, 0x00, 0x00, 0x00, 0x00, 0x02, 0xff, 0x6c, 0x92, 0x61, 0x4b, 0xfb, 0x30,
	0x10, 0xc6, 0xff, 0xfb, 0xcf, 0x75, 0xee, 0x54, 0x66, 0xe3, 0x56, 0xca, 0x60, 0xa0, 0x7d, 0x25,
	0x0a, 0x9d, 0xa8, 0x2f, 0x7c, 0xab, 0x0e, 0xa4, 0x08, 0x0a, 0xfd, 0x02, 0x25, 0x4d, 0x32, 0x09,
	0xb8, 0xa4, 0x34, 0xa9, 0xe0, 0x47, 0xf2, 0x5b, 0x4a, 0x2f, 0x29, 0xae, 0xe2, 0xbb, 0xf6, 0x79,
	0x9e, 0xdf, 0xdd, 0x71, 0x17, 0x58, 0x54, 0xb5, 0xb6, 0x7a, 0x55, 0xea, 0x46, 0x31, 0xb1, 0x32,
	0xa2, 0xfe, 0x90, 0x4c, 0xa4, 0x28, 0x92, 0xc0, 0xa9, 0x49, 0x0a, 0x47, 0x0f, 0xf8, 0xf5, 0x24,
	0xec, 0x9a, 0x5a, 0x4a, 0x96, 0x00, 0x94, 0x31, 0xdd, 0x28, 0x5b, 0x48, 0x1e, 0x0f, 0x4e, 0x07,
	0xe7, 0xa3, 0x7c, 0xe2, 0x95, 0x8c, 0x27, 0x5f, 0x43, 0x98, 0xf7, 0x80, 0x5c, 0x98, 0x4a, 0x2b,
	0x23, 0x48, 0x04, 0x41, 0x2d, 0xa8, 0xd1, 0x0a, 0xa1, 0x49, 0xee, 0xff, 0xc8, 0x05, 0x84, 0xae,
	0x57, 0xc1, 0xde, 0xa9, 0x31, 0x85, 0xa2, 0x5b, 0x11, 0xff, 0xc7, 0xc8, 0xd4, 0x19, 0x8f, 0xad,
	0xfe, 0x42, 0xb7, 0x82, 0xdc, 0x41, 0xdc, 0xcb, 0x72, 0x61, 0x58, 0x2d, 0x2b, 0x2b, 0xb5, 0x8a,
	0x87, 0x88, 0x44, 0x3b, 0xc8, 0xfa, 0xc7, 0x6d, 0xbb, 0x78, 0x90, 0x5a, 0xf1, 0xa6, 0xeb, 0xcf,
	0x76, 0xfa, 0x3d, 0x9c, 0x7e, 0xea, 0x08, 0xaf, 0x67, 0x9c, 0x5c, 0xc1, 0xac, 0xfc, 0x15, 0xc6,
	0xa1, 0x46, 0xd8, 0x81, 0x94, 0xbd, 0x3c, 0xce, 0x75, 0x09, 0x21, 0x0e, 0x24, 0x37, 0x92, 0xd1,
	0xb6, 0x5f, 0x5b, 0x3d, 0xc0, 0xea, 0xc7, 0x7d, 0x23, 0xe3, 0x24, 0x85, 0x13, 0xbf, 0x3f, 0x55,
	0x52, 0xc5, 0x0b, 0x57, 0x2f, 0x1e, 0x63, 0x3c, 0x74, 0x8b, 0x44, 0xc7, 0xed, 0x91, 0xdc, 0x42,
	0xe4, 0xf2, 0xba, 0xb1, 0x7a, 0xb3, 0x8b, 0xec, 0x23, 0x32, 0x43, 0xf7, 0xb5, 0x33, 0x3d, 0x75,
	0x06, 0x87, 0x8e, 0xf2, 0xd9, 0x09, 0x66, 0x0f, 0x50, 0x73, 0x91, 0xeb, 0x67, 0x08, 0x7c, 0xf8,
	0x1e, 0xc6, 0xdd, 0x7d, 0xe7, 0xa9, 0x03, 0xd2, 0xde, 0x15, 0x17, 0xcb, 0x3f, 0xe5, 0xee, 0xb8,
	0xc9, 0xbf, 0x32, 0xc0, 0x77, 0x73, 0xf3, 0x1d, 0x00, 0x00, 0xff, 0xff, 0x42, 0xae, 0x67, 0xb5,
	0x55, 0x02, 0x00, 0x00,
}

// Reference imports to suppress errors if they are not otherwise used.
var _ context.Context
var _ grpc.ClientConn

// This is a compile-time assertion to ensure that this generated file
// is compatible with the grpc package it is being compiled against.
const _ = grpc.SupportPackageIsVersion4

// BounceClient is the client API for Bounce service.
//
// For semantics around ctx use and closing/ending streaming RPCs, please refer to https://godoc.org/google.golang.org/grpc#ClientConn.NewStream.
type BounceClient interface {
	GetData(ctx context.Context, in *BounceGetData, opts ...grpc.CallOption) (*BounceGetDataResponse, error)
}

type bounceClient struct {
	cc *grpc.ClientConn
}

func NewBounceClient(cc *grpc.ClientConn) BounceClient {
	return &bounceClient{cc}
}

func (c *bounceClient) GetData(ctx context.Context, in *BounceGetData, opts ...grpc.CallOption) (*BounceGetDataResponse, error) {
	out := new(BounceGetDataResponse)
	err := c.cc.Invoke(ctx, "/bounce.Bounce/GetData", in, out, opts...)
	if err != nil {
		return nil, err
	}
	return out, nil
}

// BounceServer is the server API for Bounce service.
type BounceServer interface {
	GetData(context.Context, *BounceGetData) (*BounceGetDataResponse, error)
}

func RegisterBounceServer(s *grpc.Server, srv BounceServer) {
	s.RegisterService(&_Bounce_serviceDesc, srv)
}

func _Bounce_GetData_Handler(srv interface{}, ctx context.Context, dec func(interface{}) error, interceptor grpc.UnaryServerInterceptor) (interface{}, error) {
	in := new(BounceGetData)
	if err := dec(in); err != nil {
		return nil, err
	}
	if interceptor == nil {
		return srv.(BounceServer).GetData(ctx, in)
	}
	info := &grpc.UnaryServerInfo{
		Server:     srv,
		FullMethod: "/bounce.Bounce/GetData",
	}
	handler := func(ctx context.Context, req interface{}) (interface{}, error) {
		return srv.(BounceServer).GetData(ctx, req.(*BounceGetData))
	}
	return interceptor(ctx, in, info, handler)
}

var _Bounce_serviceDesc = grpc.ServiceDesc{
	ServiceName: "bounce.Bounce",
	HandlerType: (*BounceServer)(nil),
	Methods: []grpc.MethodDesc{
		{
			MethodName: "GetData",
			Handler:    _Bounce_GetData_Handler,
		},
	},
	Streams:  []grpc.StreamDesc{},
	Metadata: "proto/bounce/service.proto",
}
