// Code generated by protoc-gen-go. DO NOT EDIT.
// source: service.proto

package bounce

import (
	fmt "fmt"
	proto "github.com/golang/protobuf/proto"
	math "math"
)

// Reference imports to suppress errors if they are not otherwise used.
var _ = proto.Marshal
var _ = fmt.Errorf
var _ = math.Inf

// This is a compile-time assertion to ensure that this generated file
// is compatible with the proto package it is being compiled against.
// A compilation error at this line likely means your copy of the
// proto package needs to be updated.
const _ = proto.ProtoPackageIsVersion3 // please upgrade the proto package

type BounceGetData struct {
	AccountId            int32    `protobuf:"varint,1,opt,name=account_id,json=accountId,proto3" json:"account_id,omitempty"`
	XXX_NoUnkeyedLiteral struct{} `json:"-"`
	XXX_unrecognized     []byte   `json:"-"`
	XXX_sizecache        int32    `json:"-"`
}

func (m *BounceGetData) Reset()         { *m = BounceGetData{} }
func (m *BounceGetData) String() string { return proto.CompactTextString(m) }
func (*BounceGetData) ProtoMessage()    {}
func (*BounceGetData) Descriptor() ([]byte, []int) {
	return fileDescriptor_a0b84a42fa06f626, []int{0}
}

func (m *BounceGetData) XXX_Unmarshal(b []byte) error {
	return xxx_messageInfo_BounceGetData.Unmarshal(m, b)
}
func (m *BounceGetData) XXX_Marshal(b []byte, deterministic bool) ([]byte, error) {
	return xxx_messageInfo_BounceGetData.Marshal(b, m, deterministic)
}
func (m *BounceGetData) XXX_Merge(src proto.Message) {
	xxx_messageInfo_BounceGetData.Merge(m, src)
}
func (m *BounceGetData) XXX_Size() int {
	return xxx_messageInfo_BounceGetData.Size(m)
}
func (m *BounceGetData) XXX_DiscardUnknown() {
	xxx_messageInfo_BounceGetData.DiscardUnknown(m)
}

var xxx_messageInfo_BounceGetData proto.InternalMessageInfo

func (m *BounceGetData) GetAccountId() int32 {
	if m != nil {
		return m.AccountId
	}
	return 0
}

type BounceGetDataResponse struct {
	Reason                 string   `protobuf:"bytes,1,opt,name=reason,proto3" json:"reason,omitempty"`
	BounceClassName        string   `protobuf:"bytes,2,opt,name=bounce_class_name,json=bounceClassName,proto3" json:"bounce_class_name,omitempty"`
	BounceClassDescription string   `protobuf:"bytes,3,opt,name=bounce_class_description,json=bounceClassDescription,proto3" json:"bounce_class_description,omitempty"`
	OunceCategoryId        int32    `protobuf:"varint,4,opt,name=ounce_category_id,json=ounceCategoryId,proto3" json:"ounce_category_id,omitempty"`
	BounceCategoryName     string   `protobuf:"bytes,5,opt,name=bounce_category_name,json=bounceCategoryName,proto3" json:"bounce_category_name,omitempty"`
	ClassificationId       int32    `protobuf:"varint,6,opt,name=classification_id,json=classificationId,proto3" json:"classification_id,omitempty"`
	CountInbandBounce      int32    `protobuf:"varint,7,opt,name=count_inband_bounce,json=countInbandBounce,proto3" json:"count_inband_bounce,omitempty"`
	CountOutofbandBounce   int32    `protobuf:"varint,8,opt,name=count_outofband_bounce,json=countOutofbandBounce,proto3" json:"count_outofband_bounce,omitempty"`
	CountBounce            int32    `protobuf:"varint,9,opt,name=count_bounce,json=countBounce,proto3" json:"count_bounce,omitempty"`
	XXX_NoUnkeyedLiteral   struct{} `json:"-"`
	XXX_unrecognized       []byte   `json:"-"`
	XXX_sizecache          int32    `json:"-"`
}

func (m *BounceGetDataResponse) Reset()         { *m = BounceGetDataResponse{} }
func (m *BounceGetDataResponse) String() string { return proto.CompactTextString(m) }
func (*BounceGetDataResponse) ProtoMessage()    {}
func (*BounceGetDataResponse) Descriptor() ([]byte, []int) {
	return fileDescriptor_a0b84a42fa06f626, []int{1}
}

func (m *BounceGetDataResponse) XXX_Unmarshal(b []byte) error {
	return xxx_messageInfo_BounceGetDataResponse.Unmarshal(m, b)
}
func (m *BounceGetDataResponse) XXX_Marshal(b []byte, deterministic bool) ([]byte, error) {
	return xxx_messageInfo_BounceGetDataResponse.Marshal(b, m, deterministic)
}
func (m *BounceGetDataResponse) XXX_Merge(src proto.Message) {
	xxx_messageInfo_BounceGetDataResponse.Merge(m, src)
}
func (m *BounceGetDataResponse) XXX_Size() int {
	return xxx_messageInfo_BounceGetDataResponse.Size(m)
}
func (m *BounceGetDataResponse) XXX_DiscardUnknown() {
	xxx_messageInfo_BounceGetDataResponse.DiscardUnknown(m)
}

var xxx_messageInfo_BounceGetDataResponse proto.InternalMessageInfo

func (m *BounceGetDataResponse) GetReason() string {
	if m != nil {
		return m.Reason
	}
	return ""
}

func (m *BounceGetDataResponse) GetBounceClassName() string {
	if m != nil {
		return m.BounceClassName
	}
	return ""
}

func (m *BounceGetDataResponse) GetBounceClassDescription() string {
	if m != nil {
		return m.BounceClassDescription
	}
	return ""
}

func (m *BounceGetDataResponse) GetOunceCategoryId() int32 {
	if m != nil {
		return m.OunceCategoryId
	}
	return 0
}

func (m *BounceGetDataResponse) GetBounceCategoryName() string {
	if m != nil {
		return m.BounceCategoryName
	}
	return ""
}

func (m *BounceGetDataResponse) GetClassificationId() int32 {
	if m != nil {
		return m.ClassificationId
	}
	return 0
}

func (m *BounceGetDataResponse) GetCountInbandBounce() int32 {
	if m != nil {
		return m.CountInbandBounce
	}
	return 0
}

func (m *BounceGetDataResponse) GetCountOutofbandBounce() int32 {
	if m != nil {
		return m.CountOutofbandBounce
	}
	return 0
}

func (m *BounceGetDataResponse) GetCountBounce() int32 {
	if m != nil {
		return m.CountBounce
	}
	return 0
}

type BouncePostData struct {
	AccountId              int32    `protobuf:"varint,1,opt,name=account_id,json=accountId,proto3" json:"account_id,omitempty"`
	SubAccountId           int32    `protobuf:"varint,2,opt,name=sub_account_id,json=subAccountId,proto3" json:"sub_account_id,omitempty"`
	ToEmail                string   `protobuf:"bytes,3,opt,name=to_email,json=toEmail,proto3" json:"to_email,omitempty"`
	FromEmail              string   `protobuf:"bytes,4,opt,name=from_email,json=fromEmail,proto3" json:"from_email,omitempty"`
	FromDomain             string   `protobuf:"bytes,5,opt,name=from_domain,json=fromDomain,proto3" json:"from_domain,omitempty"`
	InjectionIp            int32    `protobuf:"varint,6,opt,name=injection_ip,json=injectionIp,proto3" json:"injection_ip,omitempty"`
	RemoteIp               int32    `protobuf:"varint,7,opt,name=remote_ip,json=remoteIp,proto3" json:"remote_ip,omitempty"`
	IpPool                 string   `protobuf:"bytes,8,opt,name=ip_pool,json=ipPool,proto3" json:"ip_pool,omitempty"`
	BounceType             string   `protobuf:"bytes,9,opt,name=bounce_type,json=bounceType,proto3" json:"bounce_type,omitempty"`
	BounceClassName        string   `protobuf:"bytes,10,opt,name=bounce_class_name,json=bounceClassName,proto3" json:"bounce_class_name,omitempty"`
	BounceClassDescription string   `protobuf:"bytes,11,opt,name=bounce_class_description,json=bounceClassDescription,proto3" json:"bounce_class_description,omitempty"`
	ClassificationId       int32    `protobuf:"varint,12,opt,name=classification_id,json=classificationId,proto3" json:"classification_id,omitempty"`
	TransmissionId         int32    `protobuf:"varint,13,opt,name=transmission_id,json=transmissionId,proto3" json:"transmission_id,omitempty"`
	MessageId              int32    `protobuf:"varint,14,opt,name=message_id,json=messageId,proto3" json:"message_id,omitempty"`
	BounceReason           string   `protobuf:"bytes,15,opt,name=bounce_reason,json=bounceReason,proto3" json:"bounce_reason,omitempty"`
	Status                 string   `protobuf:"bytes,16,opt,name=status,proto3" json:"status,omitempty"`
	XXX_NoUnkeyedLiteral   struct{} `json:"-"`
	XXX_unrecognized       []byte   `json:"-"`
	XXX_sizecache          int32    `json:"-"`
}

func (m *BouncePostData) Reset()         { *m = BouncePostData{} }
func (m *BouncePostData) String() string { return proto.CompactTextString(m) }
func (*BouncePostData) ProtoMessage()    {}
func (*BouncePostData) Descriptor() ([]byte, []int) {
	return fileDescriptor_a0b84a42fa06f626, []int{2}
}

func (m *BouncePostData) XXX_Unmarshal(b []byte) error {
	return xxx_messageInfo_BouncePostData.Unmarshal(m, b)
}
func (m *BouncePostData) XXX_Marshal(b []byte, deterministic bool) ([]byte, error) {
	return xxx_messageInfo_BouncePostData.Marshal(b, m, deterministic)
}
func (m *BouncePostData) XXX_Merge(src proto.Message) {
	xxx_messageInfo_BouncePostData.Merge(m, src)
}
func (m *BouncePostData) XXX_Size() int {
	return xxx_messageInfo_BouncePostData.Size(m)
}
func (m *BouncePostData) XXX_DiscardUnknown() {
	xxx_messageInfo_BouncePostData.DiscardUnknown(m)
}

var xxx_messageInfo_BouncePostData proto.InternalMessageInfo

func (m *BouncePostData) GetAccountId() int32 {
	if m != nil {
		return m.AccountId
	}
	return 0
}

func (m *BouncePostData) GetSubAccountId() int32 {
	if m != nil {
		return m.SubAccountId
	}
	return 0
}

func (m *BouncePostData) GetToEmail() string {
	if m != nil {
		return m.ToEmail
	}
	return ""
}

func (m *BouncePostData) GetFromEmail() string {
	if m != nil {
		return m.FromEmail
	}
	return ""
}

func (m *BouncePostData) GetFromDomain() string {
	if m != nil {
		return m.FromDomain
	}
	return ""
}

func (m *BouncePostData) GetInjectionIp() int32 {
	if m != nil {
		return m.InjectionIp
	}
	return 0
}

func (m *BouncePostData) GetRemoteIp() int32 {
	if m != nil {
		return m.RemoteIp
	}
	return 0
}

func (m *BouncePostData) GetIpPool() string {
	if m != nil {
		return m.IpPool
	}
	return ""
}

func (m *BouncePostData) GetBounceType() string {
	if m != nil {
		return m.BounceType
	}
	return ""
}

func (m *BouncePostData) GetBounceClassName() string {
	if m != nil {
		return m.BounceClassName
	}
	return ""
}

func (m *BouncePostData) GetBounceClassDescription() string {
	if m != nil {
		return m.BounceClassDescription
	}
	return ""
}

func (m *BouncePostData) GetClassificationId() int32 {
	if m != nil {
		return m.ClassificationId
	}
	return 0
}

func (m *BouncePostData) GetTransmissionId() int32 {
	if m != nil {
		return m.TransmissionId
	}
	return 0
}

func (m *BouncePostData) GetMessageId() int32 {
	if m != nil {
		return m.MessageId
	}
	return 0
}

func (m *BouncePostData) GetBounceReason() string {
	if m != nil {
		return m.BounceReason
	}
	return ""
}

func (m *BouncePostData) GetStatus() string {
	if m != nil {
		return m.Status
	}
	return ""
}

type BouncePostDataResponse struct {
	Status               string   `protobuf:"bytes,1,opt,name=status,proto3" json:"status,omitempty"`
	AccountId            int32    `protobuf:"varint,2,opt,name=account_id,json=accountId,proto3" json:"account_id,omitempty"`
	XXX_NoUnkeyedLiteral struct{} `json:"-"`
	XXX_unrecognized     []byte   `json:"-"`
	XXX_sizecache        int32    `json:"-"`
}

func (m *BouncePostDataResponse) Reset()         { *m = BouncePostDataResponse{} }
func (m *BouncePostDataResponse) String() string { return proto.CompactTextString(m) }
func (*BouncePostDataResponse) ProtoMessage()    {}
func (*BouncePostDataResponse) Descriptor() ([]byte, []int) {
	return fileDescriptor_a0b84a42fa06f626, []int{3}
}

func (m *BouncePostDataResponse) XXX_Unmarshal(b []byte) error {
	return xxx_messageInfo_BouncePostDataResponse.Unmarshal(m, b)
}
func (m *BouncePostDataResponse) XXX_Marshal(b []byte, deterministic bool) ([]byte, error) {
	return xxx_messageInfo_BouncePostDataResponse.Marshal(b, m, deterministic)
}
func (m *BouncePostDataResponse) XXX_Merge(src proto.Message) {
	xxx_messageInfo_BouncePostDataResponse.Merge(m, src)
}
func (m *BouncePostDataResponse) XXX_Size() int {
	return xxx_messageInfo_BouncePostDataResponse.Size(m)
}
func (m *BouncePostDataResponse) XXX_DiscardUnknown() {
	xxx_messageInfo_BouncePostDataResponse.DiscardUnknown(m)
}

var xxx_messageInfo_BouncePostDataResponse proto.InternalMessageInfo

func (m *BouncePostDataResponse) GetStatus() string {
	if m != nil {
		return m.Status
	}
	return ""
}

func (m *BouncePostDataResponse) GetAccountId() int32 {
	if m != nil {
		return m.AccountId
	}
	return 0
}

func init() {
	proto.RegisterType((*BounceGetData)(nil), "bounce.BounceGetData")
	proto.RegisterType((*BounceGetDataResponse)(nil), "bounce.BounceGetDataResponse")
	proto.RegisterType((*BouncePostData)(nil), "bounce.BouncePostData")
	proto.RegisterType((*BouncePostDataResponse)(nil), "bounce.BouncePostDataResponse")
}

func init() { proto.RegisterFile("service.proto", fileDescriptor_a0b84a42fa06f626) }

var fileDescriptor_a0b84a42fa06f626 = []byte{
	// 562 bytes of a gzipped FileDescriptorProto
	0x1f, 0x8b, 0x08, 0x00, 0x00, 0x00, 0x00, 0x00, 0x02, 0xff, 0x94, 0x54, 0xdb, 0x8e, 0xd3, 0x30,
	0x10, 0xa5, 0x7b, 0x49, 0x9b, 0xe9, 0x6d, 0x6b, 0x96, 0x10, 0x16, 0x71, 0x2b, 0x48, 0x20, 0x90,
	0x2a, 0x04, 0x3c, 0xf0, 0x0a, 0x14, 0xa1, 0xbc, 0xb0, 0xab, 0x88, 0xf7, 0xc8, 0x49, 0xdc, 0x95,
	0x51, 0x13, 0x47, 0xb1, 0x83, 0xd4, 0x4f, 0xe1, 0x13, 0xf8, 0x0d, 0xbe, 0x0c, 0x79, 0xc6, 0xdb,
	0x4d, 0xaa, 0xb2, 0x82, 0xb7, 0xf8, 0x5c, 0x3c, 0x93, 0xe3, 0xb1, 0x61, 0xac, 0x45, 0xfd, 0x43,
	0x66, 0x62, 0x51, 0xd5, 0xca, 0x28, 0xe6, 0xa5, 0xaa, 0x29, 0x33, 0x31, 0x5f, 0xc0, 0xf8, 0x23,
	0x7e, 0x7d, 0x11, 0x66, 0xc9, 0x0d, 0x67, 0x0f, 0x00, 0x78, 0x96, 0xa9, 0xa6, 0x34, 0x89, 0xcc,
	0xc3, 0xde, 0xe3, 0xde, 0x8b, 0xe3, 0xd8, 0x77, 0x48, 0x94, 0xcf, 0x7f, 0x1d, 0xc2, 0x9d, 0x8e,
	0x21, 0x16, 0xba, 0x52, 0xa5, 0x16, 0x2c, 0x00, 0xaf, 0x16, 0x5c, 0xab, 0x12, 0x4d, 0x7e, 0xec,
	0x56, 0xec, 0x25, 0xcc, 0xa8, 0x56, 0x92, 0xad, 0xb9, 0xd6, 0x49, 0xc9, 0x0b, 0x11, 0x1e, 0xa0,
	0x64, 0x4a, 0xc4, 0x27, 0x8b, 0x7f, 0xe5, 0x85, 0x60, 0xef, 0x21, 0xec, 0x68, 0x73, 0xa1, 0xb3,
	0x5a, 0x56, 0x46, 0xaa, 0x32, 0x3c, 0x44, 0x4b, 0xd0, 0xb2, 0x2c, 0xaf, 0x59, 0x5b, 0xc5, 0x19,
	0xb9, 0x11, 0x97, 0xaa, 0xde, 0xd8, 0xee, 0x8f, 0xb0, 0xfb, 0x29, 0x39, 0x1c, 0x1e, 0xe5, 0xec,
	0x35, 0x9c, 0xa6, 0x3b, 0x62, 0x6c, 0xea, 0x18, 0x2b, 0xb0, 0xb4, 0xa3, 0xc7, 0xbe, 0x5e, 0xc1,
	0x0c, 0x1b, 0x92, 0x2b, 0x99, 0x71, 0x5b, 0xcf, 0xee, 0xee, 0xe1, 0xee, 0x27, 0x5d, 0x22, 0xca,
	0xd9, 0x02, 0x6e, 0xbb, 0xfc, 0xca, 0x94, 0x97, 0x79, 0x42, 0xfb, 0x85, 0x7d, 0x94, 0xcf, 0x28,
	0x48, 0x64, 0x28, 0x47, 0xf6, 0x0e, 0x02, 0xd2, 0xab, 0xc6, 0xa8, 0x55, 0xdb, 0x32, 0x40, 0xcb,
	0x29, 0xb2, 0xe7, 0x57, 0xa4, 0x73, 0x3d, 0x81, 0x11, 0xb9, 0x9c, 0xd6, 0x47, 0xed, 0x10, 0x31,
	0x92, 0xcc, 0x7f, 0x1f, 0xc1, 0x84, 0x3e, 0x2f, 0x94, 0xfe, 0x97, 0xd3, 0x65, 0xcf, 0x60, 0xa2,
	0x9b, 0x34, 0x69, 0x49, 0x0e, 0x50, 0x32, 0xd2, 0x4d, 0xfa, 0x61, 0xab, 0xba, 0x07, 0x03, 0xa3,
	0x12, 0x51, 0x70, 0xb9, 0x76, 0xa7, 0xd2, 0x37, 0xea, 0xb3, 0x5d, 0xda, 0xfd, 0x57, 0xb5, 0x2a,
	0x1c, 0x79, 0x84, 0xa4, 0x6f, 0x11, 0xa2, 0x1f, 0xc1, 0x10, 0xe9, 0x5c, 0x15, 0x5c, 0x96, 0x2e,
	0x70, 0x74, 0x2c, 0x11, 0xb1, 0x7f, 0x25, 0xcb, 0xef, 0x22, 0xa3, 0x8c, 0x2b, 0x97, 0xf1, 0x70,
	0x8b, 0x45, 0x15, 0xbb, 0x0f, 0x7e, 0x2d, 0x0a, 0x65, 0x84, 0xe5, 0x29, 0xd4, 0x01, 0x01, 0x51,
	0xc5, 0xee, 0x42, 0x5f, 0x56, 0x49, 0xa5, 0xd4, 0x1a, 0xc3, 0xf3, 0x63, 0x4f, 0x56, 0x17, 0x4a,
	0x61, 0x65, 0x77, 0xe6, 0x66, 0x53, 0x51, 0x5a, 0x7e, 0x0c, 0x04, 0x7d, 0xdb, 0x54, 0x62, 0xff,
	0x98, 0xc2, 0xff, 0x8f, 0xe9, 0xf0, 0xc6, 0x31, 0xdd, 0x3b, 0x48, 0xa3, 0xbf, 0x0c, 0xd2, 0x73,
	0x98, 0x9a, 0x9a, 0x97, 0xba, 0x90, 0x5a, 0x3b, 0xe9, 0x18, 0xa5, 0x93, 0x36, 0x1c, 0xe5, 0x36,
	0xf5, 0x42, 0x68, 0xcd, 0x2f, 0x85, 0xd5, 0x4c, 0xe8, 0x54, 0x1d, 0x12, 0xe5, 0xec, 0x29, 0x8c,
	0x5d, 0xbb, 0xee, 0x82, 0x4e, 0xb1, 0xc7, 0x11, 0x81, 0x31, 0x5d, 0xd3, 0x00, 0x3c, 0x6d, 0xb8,
	0x69, 0x74, 0x78, 0x42, 0xc1, 0xd1, 0x6a, 0x7e, 0x0e, 0x41, 0x77, 0x86, 0xda, 0x17, 0xde, 0x39,
	0x7a, 0x6d, 0xc7, 0xce, 0x8c, 0x1d, 0xec, 0xcc, 0xd8, 0x9b, 0x9f, 0x3d, 0xf0, 0xdc, 0x0c, 0x47,
	0xd0, 0xdf, 0x3e, 0x3b, 0x0b, 0xea, 0x66, 0xb1, 0xf7, 0x71, 0x39, 0xbb, 0x99, 0x9e, 0xdf, 0x62,
	0x4b, 0x18, 0x6c, 0x87, 0x3c, 0xe8, 0x8a, 0xaf, 0xf0, 0xb3, 0x87, 0xfb, 0xf1, 0xeb, 0x5d, 0x52,
	0x0f, 0x1f, 0xc7, 0xb7, 0x7f, 0x02, 0x00, 0x00, 0xff, 0xff, 0x31, 0x6b, 0x93, 0x47, 0x2d, 0x05,
	0x00, 0x00,
}
