// Code generated by protoc-gen-go. DO NOT EDIT.
// source: bounce/service.proto

package bounce

import (
	context "context"
	fmt "fmt"
	proto "github.com/golang/protobuf/proto"
	grpc "google.golang.org/grpc"
	math "math"
)

// Reference imports to suppress errors if they are not otherwise used.
var _ = proto.Marshal
var _ = fmt.Errorf
var _ = math.Inf

// This is a compile-time assertion to ensure that this generated file
// is compatible with the proto package it is being compiled against.
// A compilation error at this line likely means your copy of the
// proto package needs to be updated.
const _ = proto.ProtoPackageIsVersion3 // please upgrade the proto package

type BounceGetData struct {
	AccountId            int32    `protobuf:"varint,1,opt,name=account_id,json=accountId,proto3" json:"account_id,omitempty"`
	XXX_NoUnkeyedLiteral struct{} `json:"-"`
	XXX_unrecognized     []byte   `json:"-"`
	XXX_sizecache        int32    `json:"-"`
}

func (m *BounceGetData) Reset()         { *m = BounceGetData{} }
func (m *BounceGetData) String() string { return proto.CompactTextString(m) }
func (*BounceGetData) ProtoMessage()    {}
func (*BounceGetData) Descriptor() ([]byte, []int) {
	return fileDescriptor_9db8ed92e8b5a161, []int{0}
}

func (m *BounceGetData) XXX_Unmarshal(b []byte) error {
	return xxx_messageInfo_BounceGetData.Unmarshal(m, b)
}
func (m *BounceGetData) XXX_Marshal(b []byte, deterministic bool) ([]byte, error) {
	return xxx_messageInfo_BounceGetData.Marshal(b, m, deterministic)
}
func (m *BounceGetData) XXX_Merge(src proto.Message) {
	xxx_messageInfo_BounceGetData.Merge(m, src)
}
func (m *BounceGetData) XXX_Size() int {
	return xxx_messageInfo_BounceGetData.Size(m)
}
func (m *BounceGetData) XXX_DiscardUnknown() {
	xxx_messageInfo_BounceGetData.DiscardUnknown(m)
}

var xxx_messageInfo_BounceGetData proto.InternalMessageInfo

func (m *BounceGetData) GetAccountId() int32 {
	if m != nil {
		return m.AccountId
	}
	return 0
}

type BounceGetDataResponse struct {
	AccountID            int32    `protobuf:"varint,1,opt,name=AccountID,proto3" json:"AccountID,omitempty"`
	BouncesReason        string   `protobuf:"bytes,2,opt,name=BouncesReason,proto3" json:"BouncesReason,omitempty"`
	BounceClassName      string   `protobuf:"bytes,3,opt,name=BounceClassName,proto3" json:"BounceClassName,omitempty"`
	ClassificationID     int32    `protobuf:"varint,4,opt,name=ClassificationID,proto3" json:"ClassificationID,omitempty"`
	BounceType           string   `protobuf:"bytes,5,opt,name=BounceType,proto3" json:"BounceType,omitempty"`
	BounceClassDesc      string   `protobuf:"bytes,6,opt,name=BounceClassDesc,proto3" json:"BounceClassDesc,omitempty"`
	Count                int32    `protobuf:"varint,7,opt,name=Count,proto3" json:"Count,omitempty"`
	XXX_NoUnkeyedLiteral struct{} `json:"-"`
	XXX_unrecognized     []byte   `json:"-"`
	XXX_sizecache        int32    `json:"-"`
}

func (m *BounceGetDataResponse) Reset()         { *m = BounceGetDataResponse{} }
func (m *BounceGetDataResponse) String() string { return proto.CompactTextString(m) }
func (*BounceGetDataResponse) ProtoMessage()    {}
func (*BounceGetDataResponse) Descriptor() ([]byte, []int) {
	return fileDescriptor_9db8ed92e8b5a161, []int{1}
}

func (m *BounceGetDataResponse) XXX_Unmarshal(b []byte) error {
	return xxx_messageInfo_BounceGetDataResponse.Unmarshal(m, b)
}
func (m *BounceGetDataResponse) XXX_Marshal(b []byte, deterministic bool) ([]byte, error) {
	return xxx_messageInfo_BounceGetDataResponse.Marshal(b, m, deterministic)
}
func (m *BounceGetDataResponse) XXX_Merge(src proto.Message) {
	xxx_messageInfo_BounceGetDataResponse.Merge(m, src)
}
func (m *BounceGetDataResponse) XXX_Size() int {
	return xxx_messageInfo_BounceGetDataResponse.Size(m)
}
func (m *BounceGetDataResponse) XXX_DiscardUnknown() {
	xxx_messageInfo_BounceGetDataResponse.DiscardUnknown(m)
}

var xxx_messageInfo_BounceGetDataResponse proto.InternalMessageInfo

func (m *BounceGetDataResponse) GetAccountID() int32 {
	if m != nil {
		return m.AccountID
	}
	return 0
}

func (m *BounceGetDataResponse) GetBouncesReason() string {
	if m != nil {
		return m.BouncesReason
	}
	return ""
}

func (m *BounceGetDataResponse) GetBounceClassName() string {
	if m != nil {
		return m.BounceClassName
	}
	return ""
}

func (m *BounceGetDataResponse) GetClassificationID() int32 {
	if m != nil {
		return m.ClassificationID
	}
	return 0
}

func (m *BounceGetDataResponse) GetBounceType() string {
	if m != nil {
		return m.BounceType
	}
	return ""
}

func (m *BounceGetDataResponse) GetBounceClassDesc() string {
	if m != nil {
		return m.BounceClassDesc
	}
	return ""
}

func (m *BounceGetDataResponse) GetCount() int32 {
	if m != nil {
		return m.Count
	}
	return 0
}

func init() {
	proto.RegisterType((*BounceGetData)(nil), "bounce.BounceGetData")
	proto.RegisterType((*BounceGetDataResponse)(nil), "bounce.BounceGetDataResponse")
}

func init() { proto.RegisterFile("bounce/service.proto", fileDescriptor_9db8ed92e8b5a161) }

var fileDescriptor_9db8ed92e8b5a161 = []byte{
	// 252 bytes of a gzipped FileDescriptorProto
	0x1f, 0x8b, 0x08, 0x00, 0x00, 0x00, 0x00, 0x00, 0x02, 0xff, 0x6c, 0x91, 0xc1, 0x4a, 0x03, 0x31,
	0x10, 0x86, 0xdd, 0xea, 0x6e, 0xd9, 0x01, 0x51, 0x86, 0x16, 0x82, 0x58, 0x29, 0x8b, 0x87, 0xc5,
	0xc3, 0x0a, 0xfa, 0x04, 0xb5, 0x0b, 0x52, 0x04, 0x0f, 0xc1, 0xbb, 0xa4, 0xe9, 0x08, 0x01, 0x4d,
	0x96, 0x4e, 0x2a, 0xf8, 0x18, 0xbe, 0xb1, 0x34, 0x69, 0xc4, 0x6d, 0xbd, 0x65, 0x3e, 0xe6, 0xcf,
	0x47, 0xfe, 0xc0, 0x68, 0xe9, 0x36, 0x56, 0xd3, 0x2d, 0xd3, 0xfa, 0xd3, 0x68, 0x6a, 0xba, 0xb5,
	0xf3, 0x0e, 0x8b, 0x48, 0xab, 0x06, 0x4e, 0x1f, 0xc2, 0xe9, 0x91, 0x7c, 0xab, 0xbc, 0xc2, 0x09,
	0x80, 0xd2, 0xda, 0x6d, 0xac, 0x7f, 0x35, 0x2b, 0x91, 0x4d, 0xb3, 0x3a, 0x97, 0xe5, 0x8e, 0x2c,
	0x56, 0xd5, 0xf7, 0x00, 0xc6, 0xbd, 0x80, 0x24, 0xee, 0x9c, 0x65, 0xc2, 0x4b, 0x28, 0x67, 0xbb,
	0xb5, 0x36, 0xe5, 0x7e, 0x01, 0x5e, 0x27, 0x0f, 0x4b, 0x52, 0xec, 0xac, 0x18, 0x4c, 0xb3, 0xba,
	0x94, 0x7d, 0x88, 0x35, 0x9c, 0x45, 0x30, 0x7f, 0x57, 0xcc, 0xcf, 0xea, 0x83, 0xc4, 0x71, 0xd8,
	0xdb, 0xc7, 0x78, 0x03, 0xe7, 0x61, 0x30, 0x6f, 0x46, 0x2b, 0x6f, 0x9c, 0x5d, 0xb4, 0xe2, 0x24,
	0x48, 0x0f, 0x38, 0x5e, 0x01, 0xc4, 0xf8, 0xcb, 0x57, 0x47, 0x22, 0x0f, 0x17, 0xfe, 0x21, 0x7b,
	0xd6, 0x96, 0x58, 0x8b, 0xe2, 0xc0, 0xba, 0xc5, 0x38, 0x82, 0x7c, 0xbe, 0x7d, 0x90, 0x18, 0x06,
	0x55, 0x1c, 0xee, 0x9e, 0xa0, 0x88, 0x8b, 0x38, 0x83, 0x61, 0xea, 0x71, 0xdc, 0xc4, 0x86, 0x9b,
	0x5e, 0x5b, 0x17, 0x93, 0x7f, 0x71, 0x2a, 0xb1, 0x3a, 0x5a, 0x16, 0xe1, 0x7f, 0xee, 0x7f, 0x02,
	0x00, 0x00, 0xff, 0xff, 0x9c, 0x48, 0xca, 0x2e, 0xb7, 0x01, 0x00, 0x00,
}

// Reference imports to suppress errors if they are not otherwise used.
var _ context.Context
var _ grpc.ClientConn

// This is a compile-time assertion to ensure that this generated file
// is compatible with the grpc package it is being compiled against.
const _ = grpc.SupportPackageIsVersion4

// BounceClient is the client API for Bounce service.
//
// For semantics around ctx use and closing/ending streaming RPCs, please refer to https://godoc.org/google.golang.org/grpc#ClientConn.NewStream.
type BounceClient interface {
	GetData(ctx context.Context, in *BounceGetData, opts ...grpc.CallOption) (*BounceGetDataResponse, error)
}

type bounceClient struct {
	cc *grpc.ClientConn
}

func NewBounceClient(cc *grpc.ClientConn) BounceClient {
	return &bounceClient{cc}
}

func (c *bounceClient) GetData(ctx context.Context, in *BounceGetData, opts ...grpc.CallOption) (*BounceGetDataResponse, error) {
	out := new(BounceGetDataResponse)
	err := c.cc.Invoke(ctx, "/bounce.Bounce/GetData", in, out, opts...)
	if err != nil {
		return nil, err
	}
	return out, nil
}

// BounceServer is the server API for Bounce service.
type BounceServer interface {
	GetData(context.Context, *BounceGetData) (*BounceGetDataResponse, error)
}

func RegisterBounceServer(s *grpc.Server, srv BounceServer) {
	s.RegisterService(&_Bounce_serviceDesc, srv)
}

func _Bounce_GetData_Handler(srv interface{}, ctx context.Context, dec func(interface{}) error, interceptor grpc.UnaryServerInterceptor) (interface{}, error) {
	in := new(BounceGetData)
	if err := dec(in); err != nil {
		return nil, err
	}
	if interceptor == nil {
		return srv.(BounceServer).GetData(ctx, in)
	}
	info := &grpc.UnaryServerInfo{
		Server:     srv,
		FullMethod: "/bounce.Bounce/GetData",
	}
	handler := func(ctx context.Context, req interface{}) (interface{}, error) {
		return srv.(BounceServer).GetData(ctx, req.(*BounceGetData))
	}
	return interceptor(ctx, in, info, handler)
}

var _Bounce_serviceDesc = grpc.ServiceDesc{
	ServiceName: "bounce.Bounce",
	HandlerType: (*BounceServer)(nil),
	Methods: []grpc.MethodDesc{
		{
			MethodName: "GetData",
			Handler:    _Bounce_GetData_Handler,
		},
	},
	Streams:  []grpc.StreamDesc{},
	Metadata: "bounce/service.proto",
}
